export const DISPLAY_ALERT = 'SHOW_ALERT'
export const CLEAR_ALERT = 'CLEAR_ALERT'

export const REGISTER_USER_BEGIN = 'REGISTER_USER_BEGIN'
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR'

export const LOGIN_USER_BEGIN = 'LOGIN_USER_BEGIN'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR'

export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'

export const LOGOUT_USER = 'LOGOUT_USER'

export const UPDATE_USER_BEGIN = 'UPDATE_USER_BEGIN'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR'

export const SYNC_GOOGLE_BEGIN = 'SYNC_GOOGLE_BEGIN'
export const SYNC_GOOGLE_SUCCESS = 'SYNC_GOOGLE_SUCCESS'
export const SYNC_GOOGLE_ERROR = 'SYNC_GOOGLE_ERROR'

export const GET_MESSAGES_BEGIN = 'GET_MESSAGES_BEGIN'
export const GET_MESSAGES_SUCCESS = 'GET_MESSAGES_SUCCESS'

export const HANDLE_CHANGE = 'HANDLE_CHANGE'

export const GET_CONTACTS_BEGIN = 'GET_CONTACTS_BEGIN'
export const GET_CONTACTS_SUCCESS = 'GET_CONTACTS_SUCCESS'

export const SET_EDIT_CONTACTS = 'SET_EDIT_CONTACTS'

export const EDIT_CONTACT_BEGIN = 'EDIT_CONTACT_BEGIN'
export const EDIT_CONTACT_SUCCESS = 'EDIT_CONTACT_SUCCESS'
export const EDIT_CONTACT_ERROR = 'EDIT_CONTACT_ERROR'

export const SYNC_TELEGRAM_BEGIN = 'SYNC_TELEGRAM_BEGIN'
export const SYNC_TELEGRAM_SUCCESS = 'SYNC_TELEGRAM_SUCCESS'
export const SYNC_TELEGRAM_ERROR = 'SYNC_TELEGRAM_ERROR'
